/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestPostRequest {
    // HAND-PATCHED: SeerrNG book requests use string Open Library IDs, while
    // upstream Seerr movie and TV requests use numeric TMDB IDs.
    #[serde(rename = "mediaType")]
    pub media_type: MediaType,
    #[serde(rename = "mediaId")]
    pub media_id: serde_json::Value,
    #[serde(rename = "tvdbId", skip_serializing_if = "Option::is_none")]
    pub tvdb_id: Option<f64>,
    #[serde(rename = "seasons", skip_serializing_if = "Option::is_none")]
    pub seasons: Option<Box<models::RequestPostRequestSeasons>>,
    #[serde(rename = "is4k", skip_serializing_if = "Option::is_none")]
    pub is4k: Option<bool>,
    #[serde(rename = "serverId", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<f64>,
    #[serde(rename = "profileId", skip_serializing_if = "Option::is_none")]
    pub profile_id: Option<f64>,
    #[serde(rename = "rootFolder", skip_serializing_if = "Option::is_none")]
    pub root_folder: Option<String>,
    #[serde(rename = "languageProfileId", skip_serializing_if = "Option::is_none")]
    pub language_profile_id: Option<f64>,
    // HAND-PATCHED: book request fields supported by SeerrNG.
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(rename = "editionId", skip_serializing_if = "Option::is_none")]
    pub edition_id: Option<String>,
    #[serde(rename = "isbn13", skip_serializing_if = "Option::is_none")]
    pub isbn13: Option<String>,
    #[serde(rename = "authorId", skip_serializing_if = "Option::is_none")]
    pub author_id: Option<String>,
    #[serde(
        rename = "userId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_id: Option<Option<f64>>,
}

impl RequestPostRequest {
    pub fn new(
        media_type: MediaType,
        media_id: impl Into<serde_json::Value>,
    ) -> RequestPostRequest {
        RequestPostRequest {
            media_type,
            media_id: media_id.into(),
            tvdb_id: None,
            seasons: None,
            is4k: None,
            server_id: None,
            profile_id: None,
            root_folder: None,
            language_profile_id: None,
            format: None,
            edition_id: None,
            isbn13: None,
            author_id: None,
            user_id: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MediaType {
    #[serde(rename = "movie")]
    Movie,
    #[serde(rename = "tv")]
    Tv,
    #[serde(rename = "book")]
    Book,
}

impl Default for MediaType {
    fn default() -> MediaType {
        Self::Movie
    }
}

#[cfg(test)]
mod tests {
    use super::{MediaType, RequestPostRequest};

    #[test]
    fn serializes_seerrng_book_request_fields() {
        let mut request = RequestPostRequest::new(MediaType::Book, "OL45804W");
        request.format = Some("audiobook".into());
        request.isbn13 = Some("9780441478125".into());
        request.edition_id = Some("OL1M".into());
        request.author_id = Some("OL21879A".into());

        let value = serde_json::to_value(request).expect("book request should serialize");
        assert_eq!(value["mediaType"], "book");
        assert_eq!(value["mediaId"], "OL45804W");
        assert_eq!(value["format"], "audiobook");
        assert_eq!(value["isbn13"], "9780441478125");
        assert_eq!(value["editionId"], "OL1M");
        assert_eq!(value["authorId"], "OL21879A");
    }

    #[test]
    fn preserves_numeric_movie_request_ids() {
        let request = RequestPostRequest::new(MediaType::Movie, 603.0);
        let value = serde_json::to_value(request).expect("movie request should serialize");

        assert_eq!(value["mediaType"], "movie");
        assert_eq!(value["mediaId"], 603.0);
        assert!(value.get("format").is_none());
    }
}
